name: Security

on:
  push:
    branches:
      - main
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Schedule in case of no code changes
  schedule:
      - cron: '30 0 1,15 * *'

permissions:
  # Required to stop running workflows
  actions: write

jobs:
  trivy:
    name: Trivy scanner
    continue-on-error: true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      pull-requests: read

    if: (github.actor != 'dependabot[bot]')
    steps:
      -
        name: Cancel previous workflows
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      -
        uses: actions/checkout@v3
      -
        name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'
      -
        name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

  snyk:
    name: Snyk scanner
    continue-on-error: true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      pull-requests: read
      actions: write

    if: (github.actor != 'dependabot[bot]')
    steps:
      -
        name: Cancel previous workflows
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      -
        uses: actions/checkout@v3
      -
        name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk-results.sarif
      -
        name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-results.sarif

  semgrep:
    name: Static analysis (semgrep)
    continue-on-error: true
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    permissions:
      contents: read
      security-events: write
      pull-requests: read

    if: (github.actor != 'dependabot[bot]')
    steps:
      -
        name: Cancel previous workflows
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      -
        uses: actions/checkout@v3
      -
        run: semgrep ci
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      -
        name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
